export { default as Calendar } from './Calendar'
export { default as Carousel } from './Carousel'
export { default as Certifications } from './Certifications'
export { default as Date } from './Date'
export { default as Features } from './Features'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as LandingHero } from './LandingHero'
export { default as Layout } from './Layout'
export { default as Logos } from './Logos'
export { default as Maps } from './Maps'
export { default as Paragraph } from './Paragraph'
export { default as Post } from './Post'
export { default as Products } from './Products'
export { default as Table } from './Table'
export { default as Team } from './Team'
export { default as Testimonials } from './Testimonials'
export { default as News } from './News'
export { default as SwiperNews } from './SwiperNews'
export { default as NewsCard } from './NewsCard'
export { default as Featured } from './Featured'
export { default as NocturnalHero } from './NocturnalHero.jsx'
export { default as NocturnalHeroScreen } from './NocturnalHeroScreen.jsx'
export { default as NavBar } from './NavBar'
export { default as Sponsor } from './Sponsor'
export { default as Elements } from './Elements'
export { default as ElementsCard } from './ElementsCard'
export { default as Credits } from './Credits'
export { default as Test } from './Test'
export { default as NewsWall } from './NewsWall.jsx'
export { default as NewsArchiveHero } from './NewsArchiveHero.jsx'
export { default as GoogleAnalytics } from './GoogleAnalytics'

// Pagine di sezione (storia, gruppi, compagnia teatrale)
export { default as SezioneHero } from './sezione/SezioneHero.jsx'
export { default as SezioneIntestazione } from './sezione/SezioneIntestazione.jsx'
export { default as AvvisoCostruzione } from './sezione/AvvisoCostruzione.jsx'
export { default as Prosa } from './sezione/Prosa.jsx'
export { default as Cronologia } from './sezione/Cronologia.jsx'
export { default as Scaffale } from './sezione/Scaffale.jsx'
export { default as SchedaIntervista } from './sezione/SchedaIntervista.jsx'
export { default as NewsTag } from './sezione/NewsTag.jsx'
export { default as GruppiOratorio } from './GruppiOratorio.jsx'

// Reference:
// https://sunnysingh.io/blog/javascript-import-from-folder
// Spiega anche come esportare più componenti (named e default) dallo stesso file
